export const SET_USERS = 'SET_USERS';
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED';

export const SET_USER_CARD = 'SET_USER_CARD';
export const FETCH_USER_CARD_FAILED = 'FETCH_USER_CARD_FAILED';
export const FETCH_USER_CARD_START = 'FETCH_USER_CARD_START';

export const SET_REPOS = 'FETCH_REPOS';
export const FETCH_REPOS_FAILED = 'FETCH_REPOS_FAILED';
export const FETCH_REPOS_START = 'FETCH_REPOS_START';

export const SET_CURRENT_REPO = 'SET_CURRENT_REPO';
export const SET_REPO_CONTENT = 'SET_REPO_CONTENT';
export const FETCH_REPO_CONTENT_FAILED = 'FETCH_REPO_CONTENT_FAILED';
export const FETCH_REPO_CONTENT_START = 'FETCH_REPO_CONTENT_START';
export const SET_REPO_README = 'SET_REPO_README';
export const FETCH_REPO_README_FAILED = 'FETCH_REPO_README_FAILED';
export const FETCH_REPO_README_START = 'FETCH_REPO_README_START';


